server:
  security:
    authentication:
      whitelist:
        - /public/**
        - /test/**
      private:
        header-key: Api-Key
        secret-key: tuanm-auth-secret
      jwt:
        validity-in-seconds: 3600
        secret-key: tuanm-token-secret

api:
  posts:
    generator:
      lorem-ipsum:
        url: https://jaspervdj.be/lorem-markdownum/markdown.txt

logging:
  file:
    name: logs/demo.log
  level:
    root: INFO
    dev.tuanm.demo: DEBUG

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:
    ttl:
      default-in-seconds: 3600
      posts-view: 7200
      posts-search: 300
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # order_inserts: true
        jpa:
          batch_size: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123@
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
